version: '3'
volumes:
  node_modules:
services:
  node:
    build:
      context: .
      dockerfile: ./docker/dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    tty: true
    user: "${USER_ID}:${GROUP_ID}"
